steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nitor-backend', '-f', 'infrastructure/docker/Dockerfile.backend', 'packages/backend']

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nitor-frontend', '-f', 'infrastructure/docker/Dockerfile.frontend', 'packages/frontend']

  # Build AI Service
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/nitor-ai-service', '-f', 'infrastructure/docker/Dockerfile.ai-service', 'packages/ai-service']

images:
  - 'gcr.io/$PROJECT_ID/nitor-backend'
  - 'gcr.io/$PROJECT_ID/nitor-frontend'
  - 'gcr.io/$PROJECT_ID/nitor-ai-service'
